version: "3.8"
services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    working_dir: /test
    volumes:
      - ./:/test
      - ./db:/var/lib/mysql
    ports:
      - "43306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    container_name: mysql_transaction
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
volumes:
  db:
